### ISSUE TITLE
Changement de langues

### ISSUE THREAD

**Issue by AxelANGENAULT** [AriiPortal/Arii#2]
Voici les résultats des tests menés sur le changement de langue.

#### Si dans "~/Symfony/app/config/config.yml"  `locale: fr`
- Lors du switch vers "en" seul une partie des textes sont traduits (i.e. nom de module),
l'autre partie reste en français (i.e. colonnes du Suivi).

#### Si dans "~/Symfony/app/config/config.yml"  `locale: en`
- L'entièreté des textes sont en anglais.
- Le switch ne fonctionne pas ni dans la page "login" (`/app.php/login`), ni dans la page "navigation" (`URL = /app.php/?_locale=fr`), mais fonctionne quand on se place dans un module.
- Lors du switch vers "fr" (fait depuis un module) l'entièreté des textes sont en français (pour toute les pages).

#### Si dans "~/Symfony/app/config/config.yml"  `locale: de`
- Seul une petite partie des textes sont en allemand (i.e. ordre = Auftrag).
- Lors du switch vers "en" seul une partie des textes sont traduits (i.e. nom de module),
une petite partie des textes restent en allemand (i.e. ordre = Auftrag).
- Lors du switch vers "fr" l'entièreté des textes sont en français.

#### Si dans "~/Symfony/app/config/config.yml"  `locale: azerty` ou vide
Symfony remonte une erreur 404

#### Si dans "~/Symfony/app/config/config.yml"  `locale: azerty` ou `locale: de` & `default_locale:  en`
Le portail se comporte comme dans le cas n°2 (`locale: en`)

#### Si dans "~/Symfony/app/config/config.yml"  `locale: fr` & `default_locale:  en`
Le portail se comporte comme dans le cas n°2 (`locale: en`), ne tenant pas compte de la configuration demandée.

La configuration par défaut devrait être `en` et n’être prise en compte que si `local` est différent de `fr`

**Comment by AriiPortal** [comment]
1) Seules langues suivantes sont attendues: en|fr|es|de|cn|ar|ru|jp 
Pour en ajouter d'autres, il faut l'indiquer dans le fichier routing.yml. Un test avec "azerty" conduira donc à un 404
2) Les fichiers de langues doivent être remplie pour chaque langue, cela ne dépend pas du dev mais de l'équipe de traduction ou des volontaires souhaitant participer au projet

Au niveau du développement, les textes sont généralement en anglais avec un fichier pour le français. Pour le reste, ce sont des fichiers à remplir. 
Si le routage est correct,  les fichiers de traduction renseignés, et que la traduction n'apparait pas, là c'est vraiment un bug.

**Comment by AxelANGENAULT** [comment]
Bonjour,

Les routages anglais et français existent.
Le fichier message.en.yml contient `My.account: My account` ,
le fichier message.fr.yml contient `My.account: Mon compte`.

En configuration, `locale: fr` nous avons "Mon compte" ,
après le switch en anglais nous avons toujours "Mon compte".

En configuration, `locale: en` nous avons "My account"
puis lors du switch en français nous avons bien "Mon compte".

La variable `locale:` n'est pas prise en compte si `default_locale:` est définie.
