### ISSUE TITLE
Dépendance pendant mise à jours 

### ISSUE THREAD

**Issue by AxelANGENAULT** [AriiPortal/Arii#3]
L'un de nos utilisateurs a mis à jours la machine virtuel à l'aide d'une archive arii-master.zip.

Cette procédure à été infructueuse suite à un changement de dépendance,
il me semble que cela nécessite de downgrade le fichier de routing.

`CRITICAL - Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "arii_Tools_silent" as such route does not exist.") in "FOSUserBundle:Security:login.html.twig" at line 115." at /home/arii/Symfony/app/cache/dev/classes.php line 4777`

Vaut-il mieux favorisé la commande `git clone` module par module ?

Cela viens appuyer le besoin de mettre à jours le répertoire AriiPortal/Arii.
Il m'est impossible de m’occuper de cela pour le moment (J'attends l'opticien du DNS).

**Comment by AriiPortal** [comment]
Le master est un snapshot qui a été fait il y a 5 mois, on peut certainement l'utiliser comme socle mais pas comme mise à jour, ce serait un retour arrière.
Le mieux serait de proposer arii dans une installation par composer et par une utilisation judicieuse des sous-modules mais il nous manque les volontaires pour cette partie. Toute aide est bienvenue.
Le git clone pour l'installation et les git pull pour les mises à jour restent évidemment la meilleure solution.
