### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by jfpace** [AriiPortal/Arii#5]
Dans la liste des liens proposés à coté dui bouton Home; peut-on ajouter un lien vers le wiki qui contient la documentation du produit ? 
merci,
jf

**Comment by AriiPortal** [comment]
Bonjour,

Quelle est l'url à utiliser ?

Merci,
Eric

**Comment by jfpace** [comment]
Bonjour
Voici : http://wiki.sos-paris.com/index.php/Accueil
Bonne journée.
jf

**Comment by AriiPortal** [comment]
C'est fait mais c'est un peu perturbant d'arriver d'arriver sur un accueil mélangeant le portail et d'autres outils, il eut mieux valu dédier une page par module et arriver directement sur la documentation qui correspond au contexte d'utilisation.
