### ISSUE TITLE
Comment modifier les couleurs des interfaces en fonction des moteurs afin de clairement distinguer les connections à des environnements de prod/preprod/recette ?

### ISSUE THREAD

**Issue by jfpace** [AriiPortal/Arii#6]

**Comment by AriiPortal** [comment]
Si c'est au niveau du moteur jobscheduler:
http://wiki.sos-paris.com/index.php/Identifier_les_moteurs_en_changeant_la_couleur_de_fond

Sinon, il faudrait une copie d'écran pour mieux comprendre ce qu'il faut accentuer.

**Comment by jfpace** [comment]
Non, un bandeau de couleur est bien adpaté.
